const athletes = [
  // Current Athletes
  {
    firstName: "Abigail",
    lastName: "Strate",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Adrian",
    lastName: "Tittel",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Alina",
    lastName: "Nußbicker",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Alma",
    lastName: "Siegismund",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Anna",
    lastName: "Hollandt",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Anna-Fay",
    lastName: "Scharfenberg",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Bernd",
    lastName: "Schneider",
    achievements: [],
    sportDiscipline: "Fußball",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Fußballer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Cindy",
    lastName: "Haasch",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordische Kombiniererin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "David",
    lastName: "Mach",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Emely",
    lastName: "Schumann",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Emely",
    lastName: "Torazza",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Eric",
    lastName: "Frenzel",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Felix",
    lastName: "Hoffmann",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Janina",
    lastName: "Hettich-Walz",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Jenny",
    lastName: "Nowak",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordische Kombiniererin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Josephine",
    lastName: "Pagnier",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Julia",
    lastName: "Thannheimer",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Julian",
    lastName: "Schmid",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Julijan",
    lastName: "Smid",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "12.06.2003",
    club: "SV Achomitz/SD Zahomc",
    interests: ["Fußball", "Tennis", "Eishockey"],
    profession: "Skispringer",
    hobby: "Tennis, Fußball, Golf",
    portraitImageURL:
      "https://res.cloudinary.com/dbpoconup/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1740658928/Smid_Julijan_portrait_ibtlcs.jpg",
    actionImageURL: "https://res.cloudinary.com/dbpoconup/image/upload/v1740658928/Smid_Julijan_action_w2nuyl.jpg",
  },
  {
    firstName: "Justin",
    lastName: "Lisso",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Karl",
    lastName: "Geiger",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Lara",
    lastName: "Malisner",
    achievements: [],
    sportDiscipline: "Track and Field",
    birthday: "14.04.2000",
    club: "Guardia di finanza",
    interests: ["Sport allgemein"],
    profession: "Sportler",
    hobby: "Alpine skiing, ski mountaineering, hiking, baking/cooking",
    portraitImageURL:
      "https://res.cloudinary.com/dbpoconup/image/upload/w_1000,ar_1:1,c_fill,g_auto,/v1740660815/Malisner_lara_portrait_angepasst_inreco.jpg",
    actionImageURL: "https://res.cloudinary.com/dbpoconup/image/upload/v1740658934/Malisner_Lara_action_wj7vcc.jpg",
  },
  {
    firstName: "Lara",
    lastName: "Malsiner",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Lia",
    lastName: "Böhme",
    achievements: [],
    sportDiscipline: "Spezialspringen",
    birthday: "16.07.2005",
    club: "VSC-Klingenthal",
    interests: ["Sport"],
    profession: "Schülerin",
    hobby: "Schwimmen, Volleyball",
    portraitImageURL: "https://res.cloudinary.com/dbpoconup/image/upload/v1740658921/Boehme_Lia_portrait_d5ncp0.jpg",
    actionImageURL: "https://res.cloudinary.com/dbpoconup/image/upload/v1740658922/Boehme_Lia_action_jy2x0c.jpg",
  },
  {
    firstName: "Luisa",
    lastName: "Görlich",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Maria",
    lastName: "Gerboth",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordische Kombiniererin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Martin",
    lastName: "Hamann",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Martina",
    lastName: "Ertl",
    achievements: [],
    sportDiscipline: "Ski Alpin",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skirennläuferin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Pauline",
    lastName: "Eichhorn",
    achievements: [],
    sportDiscipline: "Skispringen",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skispringerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Ramona",
    lastName: "Hofmeister",
    achievements: [],
    sportDiscipline: "Snowboard",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Snowboarderin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Ronja",
    lastName: "Loh",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordische Kombiniererin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Simon",
    lastName: "Mach",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Tristan",
    lastName: "Sommerfeldt",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  {
    firstName: "Wendelin",
    lastName: "Thannheimer",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
  },
  // Former Athletes
  {
    firstName: "Andrea",
    lastName: "Henkel",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Anja",
    lastName: "Pärson",
    achievements: [],
    sportDiscipline: "Ski Alpin",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Skirennläuferin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Björn",
    lastName: "Kircheisen",
    achievements: [],
    sportDiscipline: "Nordische Kombination",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Nordischer Kombinierer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Julia",
    lastName: "Görges",
    achievements: [],
    sportDiscipline: "Tennis",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Tennisspielerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Kirsten",
    lastName: "Flipkens",
    achievements: [],
    sportDiscipline: "Tennis",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Tennisspielerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Lars",
    lastName: "Bender",
    achievements: [],
    sportDiscipline: "Fußball",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Fußballer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Lucie",
    lastName: "Safarova",
    achievements: [],
    sportDiscipline: "Tennis",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Tennisspielerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Magdalena",
    lastName: "Neuner",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Mandy",
    lastName: "Minella",
    achievements: [],
    sportDiscipline: "Tennis",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Tennisspielerin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Martina",
    lastName: "Glagow",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Martina",
    lastName: "Seidl",
    achievements: [],
    sportDiscipline: "Biathlon",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Biathletin",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Red Bull",
    lastName: "Toro Rosso",
    achievements: [],
    sportDiscipline: "Formel 1",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Rennstall",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Sven",
    lastName: "Bender",
    achievements: [],
    sportDiscipline: "Fußball",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Fußballer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Sven-Göran",
    lastName: "Eriksson",
    achievements: [],
    sportDiscipline: "Fußball",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Fußballtrainer",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
  {
    firstName: "Tennis Academy",
    lastName: "Stefan Edberg",
    achievements: [],
    sportDiscipline: "Tennis",
    birthday: "",
    club: "",
    interests: ["Sport"],
    profession: "Tennisakademie",
    hobby: "",
    portraitImageURL: "",
    actionImageURL: "",
    isFormer: true,
  },
];

export default athletes;
